version: 0.2

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      - unzip terraform_0.11.11_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_0.11.11_linux_amd64.zip
      - echo "Prepare terraform file"
      - cd module
      - terraform init
  build:
    commands:
      - terraform plan -no-color
      - terraform apply -auto-approve -no-color
  post_build:
    commands:
      - terraform destroy -auto-approve -no-color
      - echo "Nothing to do in the post_build for now"
